// <auto-generated />
namespace RestaurantWebsite.Migrations.RestaurantMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ChangeReferenceToRestPictureToFilePath : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangeReferenceToRestPictureToFilePath));
        
        string IMigrationMetadata.Id
        {
            get { return "201802050620133_ChangeReferenceToRestPictureToFilePath"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
